name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  release:
    uses: Start9Labs/start-technologies/.github/workflows/release.yml@master
    secrets:
      DEV_KEY: ${{ secrets.DEV_KEY }}
